# Generated by Django 5.2.6 on 2025-09-09 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('doctor', 'doctor'), ('expert', 'expert'), ('student', 'student'), ('researcher', 'researcher'), ('others', 'others')], default='student', max_length=50, null=True)),
                ('field_of_study', models.CharField(blank=True, choices=[('Pathology', 'pathology'), ('Histopathology', 'histopathology'), ('Oncology', 'Oncology'), ('Hematology', 'Hematology'), ('Neurology', 'Neurology'), ('Pulmonology', 'Pulmonology'), ('Medicine researches', 'Medicine researches'), ('Genetic', 'Genetic'), ('Computer science', 'AI'), ('others', 'others')], default='pathology', max_length=50, null=True)),
                ('academy', models.CharField(blank=True, help_text='school, college, hospital, ...', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
